modLoader = "javafml"
loaderVersion = "[36,)"
license = "MIT"
issueTrackerURL = "https://github.com/Franckyi/IBE-Editor/issues"

[[mods]]
modId = "guapi"
version = "${file.jarVersion}"
displayName = "GUAPI"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/ibe-editor"
authors = "Franckyi"
description = "A Minecraft GUI API inspired by JavaFX"

[[dependencies.guapi]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.guapi]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.guapi]]
modId = "gameadapter"
mandatory = true
versionRange = "[${file.jarVersion}]"
ordering = "NONE"
side = "BOTH"
