modLoader = "javafml"
loaderVersion = "[36,)"
license = "MIT"
issueTrackerURL = "https://github.com/Franckyi/IBE-Editor/issues"
logoFile = "logo.png"

[[mods]]
modId = "ibeeditor-forge"
version = "${file.jarVersion}"
displayName = "IBE Editor (Forge)"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/ibe-editor"
credits = "Thanks to Emex for the logo !"
authors = "Franckyi"
description = "Simple GUI Mod to edit an item, a block or an entity in your current world"

[[mods]]
modId = "guapi-vanilla-theme-forge"
version = "${file.jarVersion}"
displayName = "GUAPI: Vanilla Theme (Forge)"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/ibe-editor"
authors = "Franckyi"
description = "GUAPI extension to register the 'Vanilla' theme"

[[mods]]
modId = "guapi-forge"
version = "${file.jarVersion}"
displayName = "GUAPI (Forge)"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/ibe-editor"
authors = "Franckyi"
description = "A Minecraft GUI API inspired by JavaFX"

[[mods]]
modId = "gameadapter-forge"
version = "${file.jarVersion}"
displayName = "GameAdapter (Forge)"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/ibe-editor"
authors = "Franckyi"
description = "Dependency for GUAPI and IBE Editor"

[[dependencies.ibeeditor-forge]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"
