modLoader = "javafml"
loaderVersion = "[36,)"
license = "MIT"
issueTrackerURL = "https://github.com/Franckyi/IBE-Editor/issues"
logoFile = "logo.png"

[[mods]]
modId = "guapi-vanilla-theme"
version = "${file.jarVersion}"
displayName = "GUAPI: Vanilla Theme"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/ibe-editor"
authors = "Franckyi"
description = "Provides the vanilla (default) theme for GUAPI screens"

[[dependencies.guapi-vanilla-theme]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.guapi-vanilla-theme]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.guapi-vanilla-theme]]
modId = "guapi"
mandatory = true
versionRange = "[${file.jarVersion}]"
ordering = "NONE"
side = "BOTH"

[[dependencies.guapi-vanilla-theme]]
modId = "gameadapter"
mandatory = true
versionRange = "[${file.jarVersion}]"
ordering = "NONE"
side = "BOTH"
