modLoader = "javafml"
loaderVersion = "[36,)"
license = "MIT License"
issueTrackerURL = "https://github.com/Franckyi/IBE-Editor/issues"
logoFile = "logo.png"

[[mods]]
modId = "ibeeditor"
version = "1.2.2"
displayName = "IBE Editor"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/ibe-editor"
credits = "Thanks to Emex for the logo !"
authors = "Franckyi"
description = '''
ItemBlockEntity Editor is a useful mod for mapmakers and server admins.
It allows you to edit anything in your current world.
Simple GUIs system makes it very easy to use!
'''

[[dependencies.ibeeditor]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ibeeditor]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16,)"
ordering = "NONE"
side = "BOTH"
