modLoader = "javafml"
loaderVersion = "[36,)"
license = "MIT"
issueTrackerURL = "https://github.com/Franckyi/IBE-Editor/issues"
logoFile = "logo.png"

[[mods]]
modId = "ibeeditor"
version = "${file.jarVersion}"
displayName = "IBE Editor"
updateJSONURL = "https://raw.githubusercontent.com/Franckyi/IBE-Editor/master/forge_update.json"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/ibe-editor"
credits = "Thanks to Emex for the logo !"
authors = "Franckyi"
description = "Simple GUI Mod to edit an item, a block or an entity in your current world"

[[mods]]
modId = "guapivanillatheme"
version = "${file.jarVersion}"
displayName = "GUAPI: Vanilla Theme"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/ibe-editor"
authors = "Franckyi"
description = "Provides the vanilla (default) theme for GUAPI screens"

[[mods]]
modId = "guapi"
version = "${file.jarVersion}"
displayName = "GUAPI"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/ibe-editor"
authors = "Franckyi"
description = "A Minecraft GUI API inspired by JavaFX"

[[mods]]
modId = "gameadapter"
version = "${file.jarVersion}"
displayName = "GameAdapter"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/ibe-editor"
authors = "Franckyi"
description = "Dependency for GUAPI and IBE Editor to ensure compability between different Modding APIs"

[[dependencies.ibeeditor]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ibeeditor]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16,)"
ordering = "NONE"
side = "BOTH"
