name: Release
description: Release the mod on CurseForge and GitHub

inputs:
  branch:
    description: Branch
    required: true
  java-version:
    description: Java version
    required: true

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: ${{ inputs.branch }}

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: ${{ inputs.java-version }}
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      shell: bash
      run: chmod +x gradlew

    - name: Build and release mod
      shell: bash
      run: ./gradlew build curseforgeRelease githubRelease
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}