name: Build & release mod on CurseForge & GitHub

on:
  workflow_dispatch:
  push:
    branches:
      - '1.18'
    paths-ignore:
      - 'README.md'

jobs:
  release:
    name: Build & release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Build & release mod
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build curseforgeRelease modrinthRelease githubRelease --no-daemon
        env:
          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
